"use client";

import { FormEvent, ReactNode, useEffect, useMemo, useState } from "react";
import { api } from "../lib/api";

type Role = "admin" | "doctor";
type Me = { id:string; full_name:string; username:string; role:Role; specialty?:string; clinic_name?:string; facility_name:string };
type Clinic = { id:string; name:string; archived_at?:string };
type Doctor = { id:string; full_name:string; username:string; specialty:string; clinic_id:string; is_active:boolean };
type Subscription = { seats_total:number; seats_used:number; seats_free:number; plan:string; events:Array<{delta:number;reason:string;at:string}> };
type Template = { id:string; name:string; specialty:string; visit_type:string; origin:string; is_default:boolean; structure_json:{sections:Array<{section_key:string}>} };
type Patient = { id:string; display_name:string; hospital_mrn:string; gender:string; context:Record<string,unknown> };
type Visit = { id:string; state:string; patient_name:string; mrn:string; created_at:string };
type Guidance = { id:string; kind:string; suggestion_text:string; code_system?:string; code_value?:string; evidence_source:string; evidence_ref:string; safety_flag:boolean; status:string };
type Section = { id:string; section_key:string; content:string; original:string; guidance:Guidance[] };
type Summary = { visit:Visit; sections:Section[]; etag:string };

const ADMIN_NAV = [["/admin","⌂","لوحة الأدمن"],["/clinics","▦","العيادات"],["/doctors","♟","الدكاترة"],["/subscription","◫","المقاعد والفوترة"],["/settings","⚙","إعدادات المنشأة"],["/analytics","◔","التحليلات"],["/audit","≣","سجل التدقيق"]];
const DOCTOR_NAV = [["/doctor-home","⌂","الرئيسة"],["/visits","▤","سجل الزيارات"],["/templates","▧","القوالب"],["/new-visit","●","بدء زيارة"]];
const money = new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR"});

function Logo(){return <div className="brand"><svg className="brand-mark" viewBox="0 0 44 30"><path d="M3,26 C15,25 27,19 41,4" fill="none" stroke="#0E7C86" strokeWidth="3.4" strokeLinecap="round"/><circle cx="41" cy="4" r="2.8" fill="#C9A227"/></svg><bdi>Medify</bdi></div>}
function Head({title,sub,w}:{title:string;sub:string;w:string}){return <div className="page-head"><div><h1>{title}</h1><p>{sub}</p></div><bdi className="page-tag">{w}</bdi></div>}
function Badge({children,tone="info"}:{children:ReactNode;tone?:string}){return <span className={`badge badge-${tone}`}>{children}</span>}
function Stat({label,value,note}:{label:string;value:string|number;note:string}){return <div className="card stat"><div className="stat-label">{label}</div><div className="stat-value">{value}</div><div className="stat-note">{note}</div></div>}

export default function MedifyApp(){
  const [path,setPath]=useState("/"); const [me,setMe]=useState<Me|null>(null); const [ready,setReady]=useState(false); const [toast,setToast]=useState("");
  const go=(to:string)=>{history.pushState({},"",to);setPath(to);scrollTo(0,0)};
  useEffect(()=>{setPath(location.pathname);const onPop=()=>setPath(location.pathname);addEventListener("popstate",onPop);const token=localStorage.getItem("medify_token");if(token)api<Me>("/me").then(setMe).catch(()=>localStorage.removeItem("medify_token")).finally(()=>setReady(true));else setReady(true);return()=>removeEventListener("popstate",onPop)},[]);
  useEffect(()=>{if(toast){const id=setTimeout(()=>setToast(""),3200);return()=>clearTimeout(id)}},[toast]);
  if(!ready)return <div className="empty">جارٍ تحميل Medify…</div>;
  if(path==="/register")return <Register go={go} notify={setToast}/>;
  if(!me)return <Login go={go} onLogin={(u)=>{setMe(u);go(u.role==="admin"?"/admin":"/doctor-home")}}/>;
  const nav=me.role==="admin"?ADMIN_NAV:DOCTOR_NAV;
  const logout=()=>{localStorage.removeItem("medify_token");setMe(null);go("/")};
  return <div className="app"><header className="topbar"><Logo/><div className="top-spacer"/><div className="top-actions"><button className="icon-btn" title="الإشعارات">♢</button><button className="user-chip" onClick={()=>go("/profile")}><span>{me.full_name}</span><i className="avatar">{me.full_name.replace("د. ","").slice(0,2)}</i></button></div></header><div className="shell"><aside className="sidebar">{nav.map(n=><a key={n[0]} className={`nav-link ${path===n[0]?"active":""}`} href={n[0]} onClick={e=>{e.preventDefault();go(n[0])}}><span className="nav-icon">{n[1]}</span>{n[2]}</a>)}<div className="nav-group">الحساب</div><a className="nav-link" href="/profile" onClick={e=>{e.preventDefault();go("/profile")}}>◎ الملف الشخصي</a><button className="nav-link" style={{border:0,width:"100%",background:"transparent"}} onClick={logout}>↪ تسجيل الخروج</button></aside><main className="content"><Screen path={path} me={me} go={go} notify={setToast}/></main></div>{toast&&<div className="toast">{toast}</div>}</div>
}

function Login({go,onLogin}:{go:(p:string)=>void;onLogin:(u:Me)=>void}){
  const [facility,setFacility]=useState("demo"),[username,setUsername]=useState("doctor"),[password,setPassword]=useState("Doctor123!"),[error,setError]=useState(""),[loading,setLoading]=useState(false);
  const submit=async(e:FormEvent)=>{e.preventDefault();setLoading(true);setError("");try{const r=await api<{access_token:string;user:Me}>("/auth/login",{method:"POST",body:JSON.stringify({facility,username,password})});localStorage.setItem("medify_token",r.access_token);onLogin(r.user)}catch(x){setError(x instanceof Error?x.message:"تعذر الدخول")}finally{setLoading(false)}};
  return <div className="login-page"><section className="login-hero"><Logo/><h1>التوثيق السريري الذكي</h1><p>من الاستشارة العربية إلى ملخص <bdi>SOAP</bdi> مهيكل بإرشاد سريري وترميزي، ثم اعتماد بشري ورفع آمن.</p><div className="hero-pills"><span className="hero-pill">واجهة عربية RTL</span><span className="hero-pill">FHIR / NPHIES</span><span className="hero-pill">اعتماد بشري إلزامي</span></div></section><section className="login-panel"><form className="login-box" onSubmit={submit}><h2>تسجيل الدخول</h2><p className="muted">أدخل منشأتك وحسابك للمتابعة.</p><div className="demo-box">للعرض: <bdi>doctor / Doctor123!</bdi> أو <bdi>admin / Admin123!</bdi> والمنشأة <bdi>demo</bdi>.</div>{error&&<p style={{color:"var(--danger)"}}>{error}</p>}<div className="field"><label>المنشأة</label><input className="input ltr" value={facility} onChange={e=>setFacility(e.target.value)}/></div><div className="field"><label>اسم المستخدم</label><input className="input ltr" value={username} onChange={e=>setUsername(e.target.value)}/></div><div className="field"><label>كلمة المرور</label><input className="input ltr" type="password" value={password} onChange={e=>setPassword(e.target.value)}/></div><button className="btn btn-primary" style={{width:"100%"}} disabled={loading}>{loading?"جارٍ الدخول…":"دخول"}</button><button type="button" className="btn btn-secondary" style={{width:"100%",marginTop:9}} onClick={()=>go("/register")}>تسجيل منشأة جديدة</button></form></section></div>
}

function Register({go,notify}:{go:(p:string)=>void;notify:(s:string)=>void}){
  const [form,setForm]=useState({name:"",commercial_reg:"",slug:"",admin_name:"",username:"",password:"",seats:3}); const [step,setStep]=useState(1);
  const save=async()=>{try{await api("/facilities/register",{method:"POST",body:JSON.stringify(form)});notify("أُنشئت المنشأة بنجاح");go("/")}catch(e){notify(e instanceof Error?e.message:"تعذر التسجيل")}};
  return <div className="login-panel" style={{minHeight:"100vh"}}><div className="login-box" style={{maxWidth:620}}><Logo/><Head title="تسجيل منشأة جديدة" sub={`الخطوة ${step} من 3`} w="W-002"/><div className="progress">{[1,2,3].map(x=><i key={x} className={`progress-step ${x<step?"done":x===step?"current":""}`}/>)}</div>{step===1&&<><Field label="اسم المنشأة" value={form.name} set={v=>setForm({...form,name:v})}/><Field label="السجل التجاري" value={form.commercial_reg} set={v=>setForm({...form,commercial_reg:v})}/><Field label="معرّف المنشأة بالإنجليزية" value={form.slug} set={v=>setForm({...form,slug:v})}/></>}{step===2&&<><Field label="اسم الأدمن الكامل" value={form.admin_name} set={v=>setForm({...form,admin_name:v})}/><Field label="اسم المستخدم" value={form.username} set={v=>setForm({...form,username:v})}/><Field label="كلمة المرور" value={form.password} set={v=>setForm({...form,password:v})} type="password"/></>}{step===3&&<div className="card"><h3>المقاعد والخطة</h3><input className="input" type="number" min={1} max={500} value={form.seats} onChange={e=>setForm({...form,seats:Number(e.target.value)})}/><p>{money.format(form.seats*499)} شهرياً قبل الضريبة — الأسعار توضيحية حتى التحقق الميداني.</p></div>}<div className="actions" style={{marginTop:16}}>{step>1&&<button className="btn btn-secondary" onClick={()=>setStep(step-1)}>السابق</button>}{step<3?<button className="btn btn-primary" onClick={()=>setStep(step+1)}>التالي</button>:<button className="btn btn-success" onClick={save}>إنشاء المنشأة</button>}<button className="btn btn-secondary" onClick={()=>go("/")}>إلغاء</button></div></div></div>
}

function Field({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <div className="field"><label>{label}</label><input className="input" type={type} value={value} onChange={e=>set(e.target.value)}/></div>}
function Screen(p:{path:string;me:Me;go:(p:string)=>void;notify:(s:string)=>void}){switch(p.path){case"/profile":return <Profile me={p.me}/>;case"/admin":return <Admin go={p.go}/>;case"/clinics":return <Clinics notify={p.notify}/>;case"/doctors":return <Doctors notify={p.notify}/>;case"/subscription":return <Seats notify={p.notify}/>;case"/settings":return <Settings notify={p.notify}/>;case"/analytics":return <Analytics/>;case"/audit":return <Audit/>;case"/doctor-home":return <DoctorHome go={p.go}/>;case"/visits":return <Visits/>;case"/templates":return <Templates notify={p.notify}/>;case"/new-visit":return <NewVisit go={p.go} notify={p.notify}/>;case"/review":return <Review notify={p.notify}/>;default:return p.me.role==="admin"?<Admin go={p.go}/>:<DoctorHome go={p.go}/>}}

function Profile({me}:{me:Me}){return <><Head title="الملف الشخصي" sub="بيانات الحساب الحالي وصلاحياته" w="W-005"/><div className="grid grid-2"><div className="card"><div className="avatar" style={{width:70,height:70,fontSize:22}}>{me.full_name.slice(0,2)}</div><h2>{me.full_name}</h2><p className="muted">{me.facility_name}</p><hr/><p><b>الدور:</b> {me.role==="admin"?"أدمن":"دكتور"}</p><p><b>التخصص:</b> {me.specialty||"—"}</p><p><b>العيادة:</b> {me.clinic_name||"—"}</p></div><div className="card"><h2>تغيير كلمة المرور</h2><Field label="كلمة المرور الحالية" value="" set={()=>{}} type="password"/><Field label="كلمة المرور الجديدة" value="" set={()=>{}} type="password"/><button className="btn btn-primary">حفظ كلمة المرور</button></div></div></>}
function Admin({go}:{go:(p:string)=>void}){return <><Head title="لوحة الأدمن" sub="مجمع الشفاء الطبي — الحالة نشطة" w="W-101"/><div className="grid grid-4"><Stat label="المقاعد" value="4 / 5" note="مقعد واحد متاح"/><Stat label="حالة الربط" value="متصل" note="وضع الاختبار"/><Stat label="رفع الزيارات اليوم" value="18" note="نجح · 1 فشل"/><Stat label="الاشتراك" value="نشط" note="التجديد 1 أغسطس"/></div><div className="grid grid-2" style={{marginTop:16}}><div className="card"><h2>إجراءات سريعة</h2><div className="actions"><button className="btn btn-primary" onClick={()=>go("/doctors")}>إضافة دكتور</button><button className="btn btn-secondary" onClick={()=>go("/settings")}>اختبار الربط</button><button className="btn btn-secondary" onClick={()=>go("/analytics")}>عرض التحليلات</button></div></div><div className="card"><h2>خصوصية اللوحة</h2><p>تعرض هذه اللوحة تجميعات تشغيلية فقط. لا يستطيع الأدمن قراءة التفريغ أو الملخص أو الإرشادات السريرية.</p></div></div></>}

function Clinics({notify}:{notify:(s:string)=>void}){const [rows,setRows]=useState<Clinic[]>([]),[name,setName]=useState("");const load=()=>api<Clinic[]>("/clinics").then(setRows).catch(e=>notify(e.message));useEffect(()=>{void load()},[]);const add=async()=>{if(!name)return;await api("/clinics",{method:"POST",body:JSON.stringify({name})});setName("");void load()};return <><Head title="إدارة العيادات" sub="إنشاء وتعديل وأرشفة عيادات المنشأة" w="W-102"/><div className="card"><div className="actions"><input className="input" style={{maxWidth:330}} placeholder="اسم العيادة الجديدة" value={name} onChange={e=>setName(e.target.value)}/><button className="btn btn-primary" onClick={add}>+ إضافة</button></div></div><Table heads={["العيادة","الحالة","إجراء"]} rows={rows.map(x=>[x.name,x.archived_at?<Badge tone="danger">مؤرشفة</Badge>:<Badge tone="success">نشطة</Badge>,<button key={x.id} className="btn btn-secondary">تعديل</button>])}/></>}
function Doctors({notify}:{notify:(s:string)=>void}){const [rows,setRows]=useState<Doctor[]>([]);useEffect(()=>{api<Doctor[]>("/doctors").then(setRows).catch(e=>notify(e.message))},[]);return <><Head title="الدكاترة" sub="الحسابات وحالة استهلاك المقاعد" w="W-103 · W-104"/><Table heads={["الدكتور","المستخدم","التخصص","الحالة","إجراءات"]} rows={rows.map(x=>[x.full_name,<bdi key="u">{x.username}</bdi>,x.specialty,x.is_active?<Badge tone="success">نشط</Badge>:<Badge tone="danger">معطّل</Badge>,<button key="e" className="btn btn-secondary">تعديل</button>])}/><p className="muted">التعطيل يحرر المقعد فوراً، ولا يحذف سجل الدكتور أو زياراته.</p></>}
function Seats({notify}:{notify:(s:string)=>void}){const [s,setS]=useState<Subscription|null>(null);const load=()=>api<Subscription>("/subscription").then(setS).catch(e=>notify(e.message));useEffect(()=>{void load()},[]);if(!s)return <div className="empty">تحميل…</div>;return <><Head title="المقاعد والفوترة" sub="إدارة سعة الاشتراك وسجل التغييرات" w="W-105 · W-111"/><div className="grid grid-3"><Stat label="الإجمالي" value={s.seats_total} note={s.plan}/><Stat label="المستهلك" value={s.seats_used} note="دكاترة نشطون"/><Stat label="المتاح" value={s.seats_free} note="جاهز للتخصيص"/></div><div className="card" style={{marginTop:16}}><h2>تعديل المقاعد</h2><div className="actions"><button className="btn btn-secondary" onClick={()=>api("/subscription/seats",{method:"PATCH",body:JSON.stringify({seats_total:s.seats_total+1})}).then(()=>load())}>+ مقعد</button><button className="btn btn-secondary" disabled={s.seats_total<=s.seats_used} onClick={()=>api("/subscription/seats",{method:"PATCH",body:JSON.stringify({seats_total:s.seats_total-1})}).then(()=>load())}>− مقعد</button></div><p>التوسعة فورية، والتقليص لا يسمح بأقل من عدد الدكاترة النشطين.</p></div></>}
function Settings({notify}:{notify:(s:string)=>void}){const [tab,setTab]=useState("coding");return <><Head title="إعدادات المنشأة" sub="الترميز والربط والقوالب العامة" w="W-106 · W-107 · W-112"/><div className="tabs"><button className={`tab ${tab==="coding"?"active":""}`} onClick={()=>setTab("coding")}>أنظمة الترميز</button><button className={`tab ${tab==="integration"?"active":""}`} onClick={()=>setTab("integration")}>نظام المستشفى</button><button className={`tab ${tab==="templates"?"active":""}`} onClick={()=>setTab("templates")}>القوالب العامة</button></div><div className="card">{tab==="coding"&&<><h2>الأنظمة النشطة</h2>{["ICD-10-AM","ACHI","NDC"].map(x=><p key={x}><input type="checkbox" defaultChecked/> <bdi>{x}</bdi></p>)}</>}{tab==="integration"&&<><h2>وجهة الرفع</h2><Field label="FHIR Endpoint" value="https://his.example.sa/fhir" set={()=>{}}/><button className="btn btn-primary" onClick={()=>api<{ok:boolean}>("/settings/integration/test",{method:"POST"}).then(()=>notify("نجح اختبار الاتصال — 184ms"))}>اختبار الاتصال</button><p className="muted">الرفع التجريبي لا يرسل بيانات مرضى حقيقية.</p></>}{tab==="templates"&&<><h2>القوالب العامة</h2><p>قالب باطنة — متابعة عامة SOAP</p><p>قالب طب أسرة — زيارة أولى</p></>}</div></>}
function Analytics(){return <><Head title="التحليلات" sub="مؤشرات الاستخدام والجودة دون محتوى سريري" w="W-108 · W-109"/><div className="grid grid-4"><Stat label="زيارات الأسبوع" value="142" note="+18%"/><Stat label="متوسط المراجعة" value="1:47" note="ضمن الهدف"/><Stat label="قبول الإرشاد السريري" value="54%" note="الهدف ≥ 50%"/><Stat label="نجاح أول رفع" value="96.4%" note="الهدف ≥ 95%"/></div><div className="card" style={{marginTop:16}}><h2>قنوات التحرير</h2><p>كتابة 52% · محادثة AI 30% · إملاء صوتي 18%</p></div></>}
function Audit(){const [rows,setRows]=useState<Array<{id:string;action:string;entity:string;at:string}>>([]);useEffect(()=>{api<typeof rows>("/audit-logs").then(setRows)},[]);return <><Head title="سجل التدقيق" sub="سجل إلحاقي لا تعديل ولا حذف" w="W-110"/><Table heads={["الوقت","العملية","الكيان","المعرف"]} rows={rows.map(x=>[new Date(x.at).toLocaleString("ar-SA"),x.action,x.entity,<bdi key="id">{x.id.slice(0,8)}</bdi>])}/></>}
function DoctorHome({go}:{go:(p:string)=>void}){return <><Head title="صباح الخير، د. أحمد" sub="عيادة الباطنة — مجمع الشفاء الطبي" w="W-201"/><div className="grid grid-3"><Stat label="زيارات اليوم" value="4" note="آخر زيارة 10:22"/><Stat label="بانتظار المراجعة" value="1" note="ملخص جاهز"/><Stat label="متوسط الاعتماد" value="1:52" note="ضمن الهدف"/></div><div className="card" style={{marginTop:16}}><h2>ابدأ رحلة توثيق جديدة</h2><p>اختر المريض والقالب، ثم ابدأ التسجيل والتفريغ الفوري.</p><button className="btn btn-success" onClick={()=>go("/new-visit")}>● بدء زيارة جديدة</button></div></>}
function Visits(){const [rows,setRows]=useState<Visit[]>([]);useEffect(()=>{api<Visit[]>("/visits").then(setRows)},[]);return <><Head title="سجل زياراتي" sub="زيارات الدكتور الحالي فقط" w="W-202 · W-221"/>{rows.length?<Table heads={["الوقت","المريض","الملف","الحالة"]} rows={rows.map(x=>[new Date(x.created_at).toLocaleString("ar-SA"),x.patient_name,x.mrn,<Badge key="s" tone={x.state==="uploaded"?"success":"warn"}>{x.state}</Badge>])}/>:<div className="card empty">لا توجد زيارات بعد. ابدأ زيارة جديدة لتجربة الرحلة كاملة.</div>}</>}
function Templates({notify}:{notify:(s:string)=>void}){const [rows,setRows]=useState<Template[]>([]),[show,setShow]=useState(false),[sample,setSample]=useState("");const load=()=>api<Template[]>("/templates").then(setRows);useEffect(()=>{load().catch(e=>notify(e.message))},[]);return <><Head title="قوالب التلخيص" sub="قوالب المنشأة والقوالب الشخصية المبنية عكسياً" w="W-203 · W-204 · W-205"/><button className="btn btn-primary" onClick={()=>setShow(true)}>+ قالب عكسي</button><div className="grid grid-2" style={{marginTop:16}}>{rows.map(x=><div className="card" key={x.id}><Badge tone={x.origin==="system"?"info":"success"}>{x.origin}</Badge><h3>{x.name}</h3><p>{x.specialty} · {x.visit_type}</p>{x.is_default&&<Badge tone="warn">الافتراضي</Badge>}</div>)}</div>{show&&<div className="modal-backdrop"><div className="modal"><h2>منشئ القالب العكسي</h2><div className="field"><label>نص المثال وطريقة التلخيص</label><textarea className="input" value={sample} onChange={e=>setSample(e.target.value)}/></div><div className="actions"><button className="btn btn-primary" onClick={async()=>{const built=await api<{name:string;sections:Array<{section_key:string}>}>("/templates/reverse-build",{method:"POST",body:JSON.stringify({sample_text:sample,summarization_style:"مختصر ومنظم",specialty:"باطنة"})});await api("/templates",{method:"POST",body:JSON.stringify({name:built.name,specialty:"باطنة",visit_type:"متابعة",structure_json:{sections:built.sections},origin:"reverse_built"})});setShow(false);load();notify("حُفظ القالب الشخصي")}}>توليد وحفظ</button><button className="btn btn-secondary" onClick={()=>setShow(false)}>إلغاء</button></div></div></div>}</>}

function NewVisit({go,notify}:{go:(p:string)=>void;notify:(s:string)=>void}){const [step,setStep]=useState(1),[patients,setPatients]=useState<Patient[]>([]),[templates,setTemplates]=useState<Template[]>([]),[patient,setPatient]=useState(""),[template,setTemplate]=useState(""),[visit,setVisit]=useState(""),[seconds,setSeconds]=useState(0),[recording,setRecording]=useState(false);useEffect(()=>{api<Patient[]>("/patients").then(setPatients);api<Template[]>("/templates").then(x=>{setTemplates(x);setTemplate(x.find(t=>t.is_default)?.id||x[0]?.id||"")})},[]);useEffect(()=>{if(!recording)return;const id=setInterval(()=>setSeconds(x=>x+1),1000);return()=>clearInterval(id)},[recording]);const start=async()=>{if(!patient||!template){notify("اختر المريض والقالب أولاً");return}const v=await api<Visit>("/visits",{method:"POST",body:JSON.stringify({patient_id:patient,template_id:template})});await api(`/visits/${v.id}/recording/start`,{method:"POST"});setVisit(v.id);localStorage.setItem("medify_visit",v.id);setRecording(true);setStep(3)};const stop=async()=>{setRecording(false);await api(`/visits/${visit}/recording/stop`,{method:"POST"});notify("اكتمل الملخص والإرشاد");go("/review")};return <><Head title="بدء زيارة والتسجيل" sub="رحلة متتابعة مع حفظ سياق المريض" w="W-210 … W-213 · W-223"/><div className="progress">{[1,2,3,4,5,6,7].map(x=><i key={x} className={`progress-step ${x<step?"done":x===step?"current":""}`}/>)}</div>{step===1&&<div className="grid grid-2">{patients.map(x=><button className="card" style={{textAlign:"right",borderColor:patient===x.id?"var(--primary)":"var(--line)"}} key={x.id} onClick={()=>setPatient(x.id)}><h3>{x.display_name}</h3><p>ملف <bdi>{x.hospital_mrn}</bdi> · {x.gender}</p></button>)}<button className="btn btn-primary" disabled={!patient} onClick={()=>setStep(2)}>التالي: القالب</button></div>}{step===2&&<div className="grid grid-2">{templates.map(x=><button className="card" style={{textAlign:"right",borderColor:template===x.id?"var(--primary)":"var(--line)"}} key={x.id} onClick={()=>setTemplate(x.id)}><h3>{x.name}</h3><p>{x.specialty} · {x.visit_type}</p></button>)}<button className="btn btn-success" onClick={start}>بدء التسجيل</button></div>}{step===3&&<div className="recorder"><span className="record-dot"/> <b>يسجل الآن</b><div className="stat-value"><bdi>{String(Math.floor(seconds/60)).padStart(2,"0")}:{String(seconds%60).padStart(2,"0")}</bdi></div><div className="wave">{Array.from({length:18},(_,i)=><span key={i} style={{height:20+(i%7)*7,animationDelay:`${i*.06}s`}}/>)}</div><p>التفريغ الفوري: كيف كانت قراءات السكر والضغط في الأسبوعين الماضيين؟</p><button className="btn btn-danger" onClick={stop}>إنهاء وتوليد الملخص</button></div>}</>}
function Review({notify}:{notify:(s:string)=>void}){const visit=typeof window!=="undefined"?localStorage.getItem("medify_visit"):null;const [sum,setSum]=useState<Summary|null>(null),[busy,setBusy]=useState(false);const load=()=>visit?api<Summary>(`/visits/${visit}/summary`).then(setSum):Promise.resolve();useEffect(()=>{load().catch(e=>notify(e.message))},[visit]);const resolve=async(g:Guidance,status:string)=>{await api(`/guidance-items/${g.id}`,{method:"PATCH",body:JSON.stringify({status})});load()};const approve=async()=>{if(!visit)return;setBusy(true);try{const out=await api<{status:string;upload:{bundle_id:string}}>(`/visits/${visit}/approve`,{method:"POST"});notify(`اعتُمدت ورُفعت: ${out.upload.bundle_id}`);load()}catch(e){notify(e instanceof Error?e.message:"فشل الاعتماد")}finally{setBusy(false)}};if(!sum)return <div className="empty">{visit?"جارٍ تحميل مساحة المراجعة…":"ابدأ زيارة أولاً"}</div>;const pending=sum.sections.flatMap(s=>s.guidance).filter(g=>g.status==="pending").length;return <><Head title="مساحة المراجعة الموحدة" sub={`${sum.visit.patient_name} · ملف ${sum.visit.mrn}`} w="W-214 … W-220 · W-222 · W-224"/><div className="progress">{[1,2,3,4,5,6,7].map(x=><i key={x} className={`progress-step ${x<6?"done":x===6?"current":""}`}/>)}</div>{sum.sections.map(s=><div className="review-section" key={s.id}><div className="review-title"><bdi>{s.section_key}</bdi> {({S:"الذاتي",O:"الموضوعي",A:"التقييم",P:"الخطة"} as Record<string,string>)[s.section_key]}</div><div className="review-body"><p className="clinical-text">{s.content}</p>{s.guidance.map(g=><div className={`guidance ${g.status!=="pending"?"resolved":""}`} key={g.id}><div className="actions"><Badge tone={g.status==="pending"?"warn":"success"}>{g.status}</Badge><Badge>{g.kind}</Badge>{g.safety_flag&&<Badge tone="danger">سلامة مريض</Badge>}</div><p className="clinical-text">{g.suggestion_text}</p>{g.code_value&&<bdi>{g.code_system} · {g.code_value}</bdi>}<p className="muted">المصدر: {g.evidence_source} — {g.evidence_ref}</p>{g.status==="pending"&&<div className="actions"><button className="btn btn-success" onClick={()=>resolve(g,"accepted")}>قبول</button><button className="btn btn-danger" onClick={()=>resolve(g,"rejected")}>رفض</button></div>}</div>)}</div></div>)}<div className="card" style={{position:"sticky",bottom:12}}><div className="actions"><Badge tone={pending?"warn":"success"}>{pending?`${pending} إرشادات معلقة`:"جاهزة للاعتماد"}</Badge><button className="btn btn-success" disabled={pending>0||busy||sum.visit.state==="uploaded"} onClick={approve}>{sum.visit.state==="uploaded"?"معتمدة ومرفوعة":busy?"جارٍ الاعتماد…":"اعتمد وارفع"}</button></div><p className="muted">لا يُنشأ أي رفع قبل الاعتماد البشري الصريح.</p></div></>}
function Table({heads,rows}:{heads:string[];rows:ReactNode[][]}){return <div className="table-wrap" style={{marginTop:16}}><table className="table"><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>):<tr><td colSpan={heads.length} className="empty">لا توجد بيانات</td></tr>}</tbody></table></div>}
